# MIT License
#
# Copyright (c) 2019 g4s8
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights * to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
---
docker:
  image: g4s8/rultor-jdk11:alpine3.10
decrypt:
  settings.xml: "repo/.rultor/setting.xml.asc"
  .rultor/sonatype-pub.gpg: "repo/.rultor/sonatype-pub.gpg"
  .rultor/sonatype-sec.gpg: "repo/.rultor/sonatype-sec.gpg"
env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk
architect:
  - g4s8
merge:
  script: |
    rm -vf $HOME/.m2/settings.xml
    mvn clean install -Pqulice --errors -B --quiet
    pdd --file=/dev/null
deploy:
  script: |
    mvn clean deploy -Ppublish -pl .,oot,oot-maven-plugin --settings=/home/r/settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    mvn clean deploy -Ppublish -pl .,oot,oot-maven-plugin --settings=/home/r/settings.xml
